### 申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=KzRrr8&redirect_uri=http://www.51xuecheng.cn

<> 2023-07-14T235742.200.json


#### 密码模式
#POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=zhangsan&password=123

###校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwicGVybWlzc2lvbnNcIjpbXSxcInNleFwiOlwiMVwiLFwic3RhdHVzXCI6XCJcIixcInVzZXJuYW1lXCI6XCJ0MVwiLFwidXR5cGVcIjpcIjEwMTAwMlwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODk0MzI1MTEsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjI2OWRkNWY1LTE3ZmQtNGRmYS1hMDA3LTdkNzM0MWQ4Y2FhMiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.Hgzzs_9OHhHrUtqeccX9Qge1G8dfUMTkdrnlwIWO_Rw

<> 2023-07-15T123822.200.json

#### 密码模式 启用了数据库查询
#POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=stu1&password=111111

### 密码模式 启用了数据库查询
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"t1","password":"111111","authType":"password"}&password=111111